### PR TITLE
LP-34 - In client, limit number of active blogs depending on subscription level

### PR DESCRIPTION
**Pull request by m0g**
This PR is doing two things:

* Displaying a modal inviting the user to upgrade when trying to create more blogs than allowed.
* In blog settings, checking the number of active blogs before allowing to change the status from `archived` to `open`.

### CODE REVIEW

**Comment by m0g** [comment]
@nistormihai yes it should, but that's a different ticket: https://dev.sourcefabric.org/browse/LP-37

**Comment by m0g** [comment]
Added [LP-45](https://dev.sourcefabric.org/browse/LP-45)

**Comment by m0g** [comment]
Added [LP-36](https://dev.sourcefabric.org/browse/LP-36)

**Comment by mscam** [comment]
:+1:

**Pull request merged**
