### PR TITLE
Fix/theme template requests

### PR DESCRIPTION
**Pull request by nistormihai**

### CODE REVIEW

**Comment by m0g** [comment]
Is there a reason why we are included the build files in the git repo?

**Comment by nistormihai** [comment]
That is good point, I wanted from a long time to change this behaviour but that is a bigger/another task.

**Comment by nistormihai** [comment]
themes are dynamically added we need also a server side process to build files.

**Comment by m0g** [comment]
All right

**Comment by vladnicoara** [comment]
is there a JIRA ticket associated to this PR? it's not very obvious what you are trying to fix or why. Thanks

**Pull request closed without merging**
